package Interfaz;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maria
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        IngresarPersona = new javax.swing.JToggleButton();
        EliminarPersona = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        MostrarPersona = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelPersona = new javax.swing.JPanel();
        IngAlumno = new javax.swing.JButton();
        IngAlumnoPos = new javax.swing.JButton();
        IngDocente = new javax.swing.JButton();
        PanelAlumno = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PanelAlumnoPos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelDocente = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PanelEliminacion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelMuestra = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.lightGray);

        fondo.setBackground(new java.awt.Color(255, 255, 153));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 204));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IngresarPersona.setText("ing persona");
        IngresarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarPersonaActionPerformed(evt);
            }
        });
        PanelPrincipal.add(IngresarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 60));

        EliminarPersona.setText("eliminar persona");
        EliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPersonaActionPerformed(evt);
            }
        });
        PanelPrincipal.add(EliminarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, 70));
        PanelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, 10));

        MostrarPersona.setText("Mostrar lista");
        MostrarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPersonaActionPerformed(evt);
            }
        });
        PanelPrincipal.add(MostrarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        fondo.add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 540));

        contenido.setBackground(new java.awt.Color(153, 153, 153));
        contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("[imagen de fondo]");
        contenido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 216, -1, -1));

        jLabel3.setText("[aca se muestran los paneles]");
        contenido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 158, -1, -1));

        fondo.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 580, 540));

        PanelPersona.setBackground(new java.awt.Color(255, 204, 102));
        PanelPersona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IngAlumno.setText("Ingresar Alumno");
        IngAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngAlumnoActionPerformed(evt);
            }
        });
        PanelPersona.add(IngAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 130, 60));

        IngAlumnoPos.setText("Ingresar Alumno Posgrado");
        IngAlumnoPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngAlumnoPosActionPerformed(evt);
            }
        });
        PanelPersona.add(IngAlumnoPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 190, 70));

        IngDocente.setText("Ingresar Docente");
        IngDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngDocenteActionPerformed(evt);
            }
        });
        PanelPersona.add(IngDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 130, 60));

        fondo.add(PanelPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 580, 540));

        PanelAlumno.setBackground(new java.awt.Color(0, 153, 102));
        PanelAlumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("Nombre:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        PanelAlumno.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 170, 40));

        jLabel4.setText("Ingrese los datos del alumno");
        PanelAlumno.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 180, 40));

        fondo.add(PanelAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 580, 540));

        PanelAlumnoPos.setBackground(new java.awt.Color(255, 153, 102));
        PanelAlumnoPos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Panel alumno posgrado :D");
        PanelAlumnoPos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        fondo.add(PanelAlumnoPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 580, 540));

        PanelDocente.setBackground(new java.awt.Color(204, 153, 255));
        PanelDocente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Panel Docente :D");
        PanelDocente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        fondo.add(PanelDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 580, 540));

        PanelEliminacion.setBackground(new java.awt.Color(153, 0, 0));
        PanelEliminacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Panel de eliminacion");
        PanelEliminacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        fondo.add(PanelEliminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 580, 540));

        PanelMuestra.setBackground(new java.awt.Color(0, 153, 153));
        PanelMuestra.setForeground(new java.awt.Color(0, 153, 153));
        PanelMuestra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("PanelMuestra :D");
        PanelMuestra.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        fondo.add(PanelMuestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 580, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarPersonaActionPerformed
                    // TODO add your handling code here:
       contenido.setVisible(false);
       PanelPersona.setVisible(true);
    }//GEN-LAST:event_IngresarPersonaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void IngAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngAlumnoActionPerformed
        // TODO add your handling code here:
        contenido.setVisible(false);
       PanelPersona.setVisible(false);
       PanelAlumno.setVisible(true);
    }//GEN-LAST:event_IngAlumnoActionPerformed

    private void IngAlumnoPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngAlumnoPosActionPerformed
        // TODO add your handling code here:
         contenido.setVisible(false);
       PanelPersona.setVisible(false);
       PanelAlumno.setVisible(false);
       PanelAlumnoPos.setVisible(true);
    }//GEN-LAST:event_IngAlumnoPosActionPerformed

    private void IngDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngDocenteActionPerformed
        // TODO add your handling code here:
         contenido.setVisible(false);
       PanelPersona.setVisible(false);
       PanelAlumno.setVisible(false);
       PanelAlumnoPos.setVisible(false);
       PanelDocente.setVisible(true);
    }//GEN-LAST:event_IngDocenteActionPerformed

    private void EliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPersonaActionPerformed
        // TODO add your handling code here:
           contenido.setVisible(false);
       PanelPersona.setVisible(false);
       PanelAlumno.setVisible(false);
       PanelAlumnoPos.setVisible(false);
       PanelDocente.setVisible(false);
       PanelMuestra.setVisible(false);
       PanelEliminacion.setVisible(true);
    }//GEN-LAST:event_EliminarPersonaActionPerformed

    private void MostrarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPersonaActionPerformed
        // TODO add your handling code here:
             contenido.setVisible(false);
       PanelPersona.setVisible(false);
       PanelAlumno.setVisible(false);
       PanelAlumnoPos.setVisible(false);
       PanelDocente.setVisible(false);
       PanelMuestra.setVisible(true);
       PanelEliminacion.setVisible(false);
    }//GEN-LAST:event_MostrarPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarPersona;
    private javax.swing.JButton IngAlumno;
    private javax.swing.JButton IngAlumnoPos;
    private javax.swing.JButton IngDocente;
    private javax.swing.JToggleButton IngresarPersona;
    private javax.swing.JButton MostrarPersona;
    private javax.swing.JPanel PanelAlumno;
    private javax.swing.JPanel PanelAlumnoPos;
    private javax.swing.JPanel PanelDocente;
    private javax.swing.JPanel PanelEliminacion;
    private javax.swing.JPanel PanelMuestra;
    private javax.swing.JPanel PanelPersona;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
